### ISSUE TITLE
Implementing check and in methods

### ISSUE THREAD

**Issue by ywei2017** [troykinsella/concourse-artifactory-resource#2]
Hi, @troykinsella , any reason the check and in methods are not implemented. 

I was looking for a concourse resource type to simply pull artifactory resources, and this one I like the most, due to its simplicity and general purpose intent. So I was surprised of not finding the in/check methods.

If it's just time and capacity, will you be open for a P/R to add them -- in the most basic form.

Thanks
Yansheng

**Comment by ywei2017** [comment]
Hi, @troykinsella , can you kindly respond?

Thanks

**Comment by troykinsella** [comment]
Hi there. Thanks for the inquiry.

You've likely already seen this, but perhaps you'd have better luck using this resource, which does implement check/in: https://github.com/emerald-squad/artifactory-resource

That said, I'd be open to a PR to add them to this resource. That'd be appreciated.

**Comment by ywei2017** [comment]
Hi, @troykinsella Thanks for the consideration. I will try to put together a PR in the coming weeks, as much as time allows. I didn't go with the "artifactor-resource" is, that one is geared toward java apps. The resource type you have is more generic, which is what I need.

Thanks
Yansheng

**Comment by troykinsella** [comment]
@ywei2017 I've implemented the `check` and `in` operations, along with version strategy approach with an initial `single-file` strategy (as this satisfied my need). I chose a strategy pattern for versions as I didn't want to lock into a single limited method of manipulating artifacts, as this resource deals with "generic" artifacts, after all, which can have pretty diverse versioning requirements. 

Next, I intend to implement a version strategy that deals with multiple files that have a version embedded in the file names.

Could I ask you to document your versioning requirements here so that I can plan future strategies, please?

**Comment by ywei2017** [comment]
Hi, @troykinsella , That is great progress.

My usage case is about teams release software packages. Let's say today they have `/path/my_package-1.2.3.tgz`, and a new release comes out, will be like `/path/my_package_1.2.4.tgz`. so it will use a regex to match the names, and then extract the version, which is also used by the check method.

Thanks
Yansheng
